### ISSUE TITLE
Migration to version 8.0/9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-prestashop#17]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate to 8.0
- [x] prestashoperpconnect > connector_prestashop - By @pedrobaeza - #22 
- [x] prestashoperpconnect_catalog_manager > connector_prestashop_catalog_manager - By @pedrobaeza - #23 
- [x] prestashoperpconnect_customize_example > connector_prestashop_customize_example - By @pedrobaeza - #22 
# Migration to 9.0

Things to do:
- [x] make the module installable
- [x] use the new layout for python files
- [x] replace / do not let pop out NothingToDoJobError which is a risky exception (cancels the whole job if raised in a dependency import)
- [x] rename models such `xxxExportSynchronizer` to `xxxExporter` to follow the new connector naming
- [x] initialize a prestapyt client only once, not on every call
- [x] migrate to account.payment.mode
- [x] replace the binder by the core binder (using recordset instead of integer ids)

Remaining items moved to the pull request #24
- [x] connector_prestashop - #24
- [x] connector_prestashop_catalog_manager - #24
- [x] connector_prestashop_customize_example - #24

**Comment by ajile-in** [comment]
Hi @pedrobaeza ,

I would like to contribute to this activity, please let me know how can I help.

Regards,
Ajay

**Comment by pedrobaeza** [comment]
Hi, you can take the current work that is across the PRs and try to get it work, but for v9 is still too soon, because there is a lot of dependencies not migrated (connector, sale-workflow...). Maybe you can try in v8, and then let this prepared for v9.

**Comment by flotho** [comment]
Hi @Ajaeel , @pedrobaeza 

I also would like to migrate this part in V9.
Actually I'm wondering how to deal with sale workflow. As you probably know, Odoo v9 has no more workflow on sale.order. 
@pedrobaeza What are you recommendations? re-implement the Odoo v8 part or try to make it lighter ?
regards

**Comment by atchuthan** [comment]
@Ajaeel @flotho ongoing discussion at OCA mailing list
https://odoo-community.org/groups/contributors-15/contributors-37353?

**Comment by NVD77** [comment]
I understand that this is about connecting PrestaShop with ODOO version 9. May I ask if the connector to version 8 was already finished?

**Comment by pedrobaeza** [comment]
This issue was automatically generated. Indeed, v8 nor v9 is yet migrated.

**Comment by NVD77** [comment]
Thanks for your quick feedback! Is there any ongoing progress? Our ODOO consultant was looking on github for others to work together to migrate to version 8 yet no sufficient reply. Since we upgraded the erp to v8 we can't set up a synchronization with our PrestaShop 1.6 site.

**Comment by pedrobaeza** [comment]
Not for now, but we will propose the migration in the next months

**Comment by dalareo** [comment]
I have proposed a Prestashop-Odoo solution to one of my clients but... no connector available! He is very interested and a little financial effort will also be possible to have this done! I don't have the python knowledge enough to help you on this, @pedrobaeza 
V8 alone will be nice for me right now.

**Comment by flotho** [comment]
Hi @dalareo, this branch https://github.com/flotho/connector-prestashop/tree/8.0-parthiv-mig has been the most advanced try for porting in v8. @parthivgls has done a great job and I personnaly add some functionnality.
Sadly, it hasn't been merged (optimistic merged would have been appreciated here) in the official OCA.
regards

**Comment by dalareo** [comment]
Thanks @flotho! I am waiting for v9 to be available as it is the version my customers are using now!

**Comment by guewen** [comment]
Anyone started to work on the migration for v9? I plan to start working on it soon, so I'd want to avoid double work.

**Comment by parthivgls** [comment]
me me me .... :100:  but first connector-ecoomerce to be completed..

**Comment by pedrobaeza** [comment]
@atchuthan is also working in the migration to v9 AFAIK.

**Comment by guewen** [comment]
I'd would be glad to have a link to the branch if there is any :)

I'd like to propose a slightly different layout for the models (in fact, more an extension) than the usual one for this migration. This is a layout I used for my lasts custom connectors and it works well when we have a lot of classes for a model (we have, in the connectors):

```
connector_xyz
├── data
├── __init__.py
├── models
│   ├── __init__.py
│   ├── product_category
│   │   ├── common.py
│   │   ├── exporter.py
│   │   ├── importer.py
│   │   └── __init__.py
│   ├── product_product
│   │   ├── common.py
│   │   ├── exporter.py
│   │   ├── importer.py
│   │   └── __init__.py
│   ├── product_template
│   │   ├── common.py
│   │   ├── exporter.py
│   │   ├── importer.py
│   │   └── __init__.py
│   ├── sale_order
│   │   ├── common.py
│   │   ├── exporter.py
│   │   ├── importer.py
│   │   └── __init__.py
│   └── sale_order_line
│       ├── common.py
│       ├── exporter.py
│       ├── importer.py
│       └── __init__.py
└── views
```

`common.py` contains the `openerp.models.Model` definition/inherit and the things which are common to both the importer and the exporter (Binder, Adapter), the other files speak by themselves. Of course, you can have more or less files for a model.

**Comment by pedrobaeza** [comment]
We will release the migration to version 8 on September, with a total rework. I think you can wait until then and see our work, and then talk about it. What do you think?

**Comment by pedrobaeza** [comment]
About the layout itself, isn't too many files? Having into account that the exporter is implemented in a separated module...

**Comment by guewen** [comment]
@pedrobaeza no there are not too many files when you have a lot of classes. When I open a Python module and I see a long list of classes, with mappers, exporters, importers and so on all mixed, the only thing I think is "What a mess!". Trust me, through all the connectors I developed since years, the layout above is the result of a process to find the ideal solution. For the custom connectors I developed with that layout, I would never ever return back to a style where you have all mixed.

@pedrobaeza is your rework public? Even before all is done, I could start to work on something and assume doing some rebase at times :) Do you still use prestapyt which is hardly maintained (and if yes, did you need to modify it?)?

**Comment by pedrobaeza** [comment]
As said, it's going to be released on September (next week) as a PR here. Yes, we use prestapyt. In fact, you have a PR to approve :wink: : https://github.com/prestapyt/prestapyt/pull/34. 

Maybe we can transfer the repository to OCA.

OK about the files. You're right that we can isolate each class in a file, following OCA's guidelines.

**Comment by guewen** [comment]
@pedrobaeza okay, thanks

I merged the prestapyt PR

**Comment by guewen** [comment]
Did anyone had a look at https://github.com/openlabs/pystashop? It looks better than prestapyt IMO (as the prestapyt author, I'm allowed to say that :)). When I wrote prestapyt, working with dicts was a requirement, that's why it converts to and back from dictionaries, nowadays, making the connector's Mapper agnostic to the format would be great anyway.

**Comment by pedrobaeza** [comment]
I didn't know, but I don't have a very good feeling surrogating part of our needs to a library from OpenLabs. I remember bad experiences in the past from contributors with the Magento library. Am I wrong?

**Comment by guewen** [comment]
We use the magento python lib from OpenLabs for the Magento connector and I'm not aware of any issues, had patch(es?) merged. Also, it's open source, we would not be depending on anyone if things would go wrong.

**Comment by pedrobaeza** [comment]
OK, if you want to take a look for version 9, go ahead. We have already working everything in version 8, so now switching is a work we can't afford.

**Comment by guewen** [comment]
Absolutely, I never thought you would change for v8.0 now. I'm also not saying we should use it, but I'll evaluate the option.

**Comment by flotho** [comment]
@guewen , great news for the layout, 
I'm not so experienced in connector framework and the prestashopconnector is really a mess for someone who tried to understand how the classes are structured. 
So I really would like to cooperate on this all the more so as I've already started some migration https://github.com/flotho/connector-prestashop/
My point is how to cooperate fast? Could it be interesting to start the famous optimistic merge on a dedicated branch?
@gaelTorrecillas and I would like to give some time on this as we need this migration fast. Does anyone could propose a way to split/distribute the job?
Regards

**Comment by flotho** [comment]
Hi @sebastienbeau , @guewen , @pedrobaeza ,

Could anyone take the leadership on this migration, we really would like to contribute actively.
regards

**Comment by gurneyalex** [comment]
I just sent an email to the contributors mailing list to try and get some fresh blood on this project

**Comment by flotho** [comment]
@gurneyalex , thanks
@gaelTorrecillas and I would appreciate to give our fresh blood on this ;-)

**Comment by guewen** [comment]
@flotho as soon as the V8 one is published, I'll start to work on the V9 one. I have nothing against pushing a temporary working branch on which we merge each ones pull requests optimistically, if the PSC does not have any issue with that.

**Comment by guewen** [comment]
@pedrobaeza when do you expect to push? Sorry if I'm insistent, but I have time on my planning today and tomorrow to kick off the 9.0 migration. Nobody will blame you if the branch is not perfect yet :)

**Comment by guewen** [comment]
@pedrobaeza any review I can do on prestashop connector's dependency addons?

**Comment by pedrobaeza** [comment]
I'm doing today!

**Comment by guewen** [comment]
@pedrobaeza yeaah, looking forwards to it :)

**Comment by flotho** [comment]
Hi @pedrobaeza,

Great thanks for your PR on v8 migration with newer PS versions. We'll take care of that part.

**Comment by flotho** [comment]
Hi @guewen , @pedrobaeza ,

Did you decided to have an optimistic PR for the v9 migration. I have 1.5 devs available for the next 2 weeks and really would like to help on this.
Regards
cc @gaelTorrecillas

**Comment by guewen** [comment]
@flotho my working branch is there: https://github.com/guewen/connector-prestashop/tree/9.0-migration-connector-prestashop

I'm working on the reorganization of the files, which must be done before we can work at more than one person at a time.

**Comment by flotho** [comment]
Hi @guewen ,

If you agree, we're going to work on this with @gaelTorrecillas. regards

**Comment by gaelTorrecillas** [comment]
Hi @guewen,

In original openerp of connector-prestashop, this module depended on product_custom_attributes, 
what replaces it here? will you replace it with product_custom_info?

**Comment by pedrobaeza** [comment]
@gaelTorrecillas, that's not needed. Any specific PrestaShop information is put directly on the prestashop.product.product model (the binding).

**Comment by gaelTorrecillas** [comment]
hi,

@pedrobaeza  thank you for your answer,

@guewen, where are you with the connector prestashop migration? and do you have part on which we can work to avoid overlap with your work?

**Comment by guewen** [comment]
@gaelTorrecillas look at the description of the issue, I added some tasks, you can see my progress as I tick the boxes. I'm working on the "payment method to account.payment.mode" task. Choose a task you would be comfortable to work on, the list is not exhaustive you might have other things to do. If you'll need the "catalog" module, you could also work on it as I didn't even started.

**Comment by gaelTorrecillas** [comment]
hello,

@guewen thanks you for issue #25, I have an other question, I use your prestapyt, but it says this version isn't compatible with our version of prestashop 1.6.0.9, what is your version of prestashop used to test prestapyt in your deposit (ref : https://github.com/guewen/prestapyt/tree/use-requests)


'''
/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py:183: UserWarning: This library may not be compatible with this version of PrestaShop (1.6.0.9). Please upgrade/downgrade this library
'''

**Comment by guewen** [comment]
@gaelTorrecillas could you comment on the pull request #24 ?

**Comment by gaelTorrecillas** [comment]
yes,
sorry, I'm not on the right topic

**Comment by pedrobaeza** [comment]
As the connector is now merged, we can close this tracking issue. Thank you to all the contributors.
