### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-prestashop#27]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] connector_prestashop - By @sergio-teruel - #58 
- [ ] connector_prestashop_catalog_manager - By @bguillot - #91 
- [ ] connector_prestashop_customize_example
- [ ] connector_prestashop_manufacturer

**Comment by converge** [comment]
@pedrobaeza hello, is it hard to migrate this module to Odoo10 ? I do have programming skills, but no skills developing Odoo modules.

**Comment by pedrobaeza** [comment]
Check https://github.com/OCA/connector-prestashop/pull/58
