### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/connector-prestashop#86]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] connector_prestashop
- [ ] connector_prestashop_catalog_manager
- [ ] connector_prestashop_customize_example
- [ ] connector_prestashop_manufacturer
